export const customers = ([
    { id: 1, name: "Customer 01", title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pellentesque vehicula ante, ultrices feugiat nisi sodales at. Aliquam tristique maximus purus. Ut at mi ac lacus pulvinar porta non id eros. Pellentesque vitae sagittis felis. Nam turpis lacus, posuere vitae ligula et, vestibulum pretium ante. Ut urna lacus, lacinia a.", address: "123 Main St" },
    { id: 2, name: "Customer 02", title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pellentesque vehicula ante, ultrices feugiat nisi sodales at. Aliquam tristique maximus purus. Ut at mi ac lacus pulvinar porta non id eros. Pellentesque vitae sagittis felis. Nam turpis lacus, posuere vitae ligula et, vestibulum pretium ante. Ut urna lacus, lacinia a.", address: "456 Oak St" },
    { id: 3, name: "Customer 03", title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pellentesque vehicula ante, ultrices feugiat nisi sodales at. Aliquam tristique maximus purus. Ut at mi ac lacus pulvinar porta non id eros. Pellentesque vitae sagittis felis. Nam turpis lacus, posuere vitae ligula et, vestibulum pretium ante. Ut urna lacus, lacinia a.", address: "789 Pine St" },
    { id: 4, name: "Customer 04", title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pellentesque vehicula ante, ultrices feugiat nisi sodales at. Aliquam tristique maximus purus. Ut at mi ac lacus pulvinar porta non id eros. Pellentesque vitae sagittis felis. Nam turpis lacus, posuere vitae ligula et, vestibulum pretium ante. Ut urna lacus, lacinia a.", address: "101 Maple St" },
    { id: 5, name: "Customer 05", title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pellentesque vehicula ante, ultrices feugiat nisi sodales at. Aliquam tristique maximus purus. Ut at mi ac lacus pulvinar porta non id eros. Pellentesque vitae sagittis felis. Nam turpis lacus, posuere vitae ligula et, vestibulum pretium ante. Ut urna lacus, lacinia a.", address: "007 Bond St" },
    { id: 6, name: "Customer 06", title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pellentesque vehicula ante, ultrices feugiat nisi sodales at. Aliquam tristique maximus purus. Ut at mi ac lacus pulvinar porta non id eros. Pellentesque vitae sagittis felis. Nam turpis lacus, posuere vitae ligula et, vestibulum pretium ante. Ut urna lacus, lacinia a.", address: "666 Boss St" },
    { id: 7, name: "Customer 07", title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pellentesque vehicula ante, ultrices feugiat nisi sodales at. Aliquam tristique maximus purus. Ut at mi ac lacus pulvinar porta non id eros. Pellentesque vitae sagittis felis. Nam turpis lacus, posuere vitae ligula et, vestibulum pretium ante. Ut urna lacus, lacinia a.", address: "888 Meow St" },
    { id: 8, name: "Customer 08", title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pellentesque vehicula ante, ultrices feugiat nisi sodales at. Aliquam tristique maximus purus. Ut at mi ac lacus pulvinar porta non id eros. Pellentesque vitae sagittis felis. Nam turpis lacus, posuere vitae ligula et, vestibulum pretium ante. Ut urna lacus, lacinia a.", address: "404 Error St" },
    { id: 9, name: "Customer 09", title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pellentesque vehicula ante, ultrices feugiat nisi sodales at. Aliquam tristique maximus purus. Ut at mi ac lacus pulvinar porta non id eros. Pellentesque vitae sagittis felis. Nam turpis lacus, posuere vitae ligula et, vestibulum pretium ante. Ut urna lacus, lacinia a.", address: "500 AM St" },
    { id: 10, name: "Customer 10", title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pellentesque vehicula ante, ultrices feugiat nisi sodales at. Aliquam tristique maximus purus. Ut at mi ac lacus pulvinar porta non id eros. Pellentesque vitae sagittis felis. Nam turpis lacus, posuere vitae ligula et, vestibulum pretium ante. Ut urna lacus, lacinia a.", address: "696 Hehe St" },
    
  ]);